format long
I= imread("C:\Users\ntnbs\Downloads\sample_.jpg");
%gamma =0.3;
%pi =180;
%psi=0;
maxN = 10000;
Data1 = zeros(1,maxN);
q=1;

for bw = 1:1:5
    for theta = 0:30:180
        gb = gabor_self(I,bw,theta);
        Data1(1,q) = kurtosis(gb,1,'all');
        q=q+1;
        %yall = skewness(gb,1,'all');
        Data1(1,q) = skewness(gb,1,'all');
        q = q+1;
        %V = var(gb,1,"all");
        Data1(1,q) = var(gb,1,"all");
        q= q+1;
        %M= mean(gb,"all");
        Data1(1,q)= mean(gb,"all");
        q =q+1;
        glcm = graycomatrix(gb,'Offset',[-1 0;0 1;-1 1;-1 -1],'Symmetric',true);
        stats = graycoprops(glcm);
        %C = struct2cell(stats);
        %C(1)
        contrast = vertcat(stats.Contrast);
        Data1(1,q)= contrast(1);
        q=q+1;
        Data1(1,q)= contrast(2);
        q=q+1;
        Data1(1,q)= contrast(3);
        q=q+1;
        Data1(1,q)= contrast(4);
        q=q+1;
        correlation = vertcat(stats.Correlation);
        Data1(1,q)= correlation(1);
        q=q+1;
        Data1(1,q)= correlation(2);
        q=q+1;
        Data1(1,q)= correlation(3);
        q=q+1;
        Data1(1,q)= correlation(4);
        q=q+1;
        energy = vertcat(stats.Energy);
        Data1(1,q)= energy(1);
        q=q+1;
        Data1(1,q)= energy(2);
        q=q+1;
        Data1(1,q)= energy(3);
        q=q+1;
        Data1(1,q)= energy(4);
        q=q+1;
        homogeneity = vertcat(stats.Homogeneity);
        Data1(1,q)= homogeneity(1);
        q= q+1;
        Data1(1,q)= homogeneity(2);
        q= q+1;
        Data1(1,q)= homogeneity(3);
        q= q+1;
        Data1(1,q)= homogeneity(4);
        q= q+1;
    end
end
%Data1(1,q)= strcat(num2str("Malignant"));
Data1= Data1(1:q-1);
%C= {Data1,'Malignant'};
S = array2table(Data1);
S=[S];
V= [S];
format long
I= imread("C:\Users\ntnbs\Downloads\ID_Proof.jpg");
%gamma =0.3;
%pi =180;
%psi=0;
maxN = 10000;
Data1 = zeros(1,maxN);
q=1;
for bw = 1:1:5
    for theta = 0:30:180
        gb = gabor_self(I,bw,theta);
        Data1(1,q) = kurtosis(gb,1,'all');
        q=q+1;
        %yall = skewness(gb,1,'all');
        Data1(1,q) = skewness(gb,1,'all');
        q = q+1;
        %V = var(gb,1,"all");
        Data1(1,q) = var(gb,1,"all");
        q= q+1;
        %M= mean(gb,"all");
        Data1(1,q)= mean(gb,"all");
        q =q+1;
        glcm = graycomatrix(gb,'Offset',[-1 0;0 1;-1 1;-1 -1],'Symmetric',true);
        stats = graycoprops(glcm);
        %C = struct2cell(stats);
        %C(1)
        contrast = vertcat(stats.Contrast);
        Data1(1,q)= contrast(1);
        q=q+1;
        Data1(1,q)= contrast(2);
        q=q+1;
        Data1(1,q)= contrast(3);
        q=q+1;
        Data1(1,q)= contrast(4);
        q=q+1;
        correlation = vertcat(stats.Correlation);
        Data1(1,q)= correlation(1);
        q=q+1;
        Data1(1,q)= correlation(2);
        q=q+1;
        Data1(1,q)= correlation(3);
        q=q+1;
        Data1(1,q)= correlation(4);
        q=q+1;
        energy = vertcat(stats.Energy);
        Data1(1,q)= energy(1);
        q=q+1;
        Data1(1,q)= energy(2);
        q=q+1;
        Data1(1,q)= energy(3);
        q=q+1;
        Data1(1,q)= energy(4);
        q=q+1;
        homogeneity = vertcat(stats.Homogeneity);
        Data1(1,q)= homogeneity(1);
        q= q+1;
        Data1(1,q)= homogeneity(2);
        q= q+1;
        Data1(1,q)= homogeneity(3);
        q= q+1;
        Data1(1,q)= homogeneity(4);
        q= q+1;
    end
end
%Data1(1,q)= strcat(num2str("Malignant"));
Data1= Data1(1:q-1);
%C= {Data1,'Malignant'};
S = array2table(Data1);
%S=[S;S];
V=[V;S];


format long
I= imread("C:\Users\ntnbs\Downloads\IMG_20220608_085327139_2.jpg");
%gamma =0.3;
%pi =180;
%psi=0;
maxN = 10000;
Data1 = zeros(1,maxN);
q=1;

for bw = 1:1:5
    for theta = 0:30:180
        gb = gabor_self(I,bw,theta);
        Data1(1,q) = kurtosis(gb,1,'all');
        q=q+1;
        %yall = skewness(gb,1,'all');
        Data1(1,q) = skewness(gb,1,'all');
        q = q+1;
        %V = var(gb,1,"all");
        Data1(1,q) = var(gb,1,"all");
        q= q+1;
        %M= mean(gb,"all");
        Data1(1,q)= mean(gb,"all");
        q =q+1;
        glcm = graycomatrix(gb,'Offset',[-1 0;0 1;-1 1;-1 -1],'Symmetric',true);
        stats = graycoprops(glcm);
        %C = struct2cell(stats);
        %C(1)
        contrast = vertcat(stats.Contrast);
        Data1(1,q)= contrast(1);
        q=q+1;
        Data1(1,q)= contrast(2);
        q=q+1;
        Data1(1,q)= contrast(3);
        q=q+1;
        Data1(1,q)= contrast(4);
        q=q+1;
        correlation = vertcat(stats.Correlation);
        Data1(1,q)= correlation(1);
        q=q+1;
        Data1(1,q)= correlation(2);
        q=q+1;
        Data1(1,q)= correlation(3);
        q=q+1;
        Data1(1,q)= correlation(4);
        q=q+1;
        energy = vertcat(stats.Energy);
        Data1(1,q)= energy(1);
        q=q+1;
        Data1(1,q)= energy(2);
        q=q+1;
        Data1(1,q)= energy(3);
        q=q+1;
        Data1(1,q)= energy(4);
        q=q+1;
        homogeneity = vertcat(stats.Homogeneity);
        Data1(1,q)= homogeneity(1);
        q= q+1;
        Data1(1,q)= homogeneity(2);
        q= q+1;
        Data1(1,q)= homogeneity(3);
        q= q+1;
        Data1(1,q)= homogeneity(4);
        q= q+1;
    end
end
%Data1(1,q)= strcat(num2str("Malignant"));
Data1= Data1(1:q-1);
%C= {Data1,'Malignant'};
S = array2table(Data1);

V= [V;S];
